services:
  app1:
    build: ./app
    container_name: app1
    ports:
      - '${APP1_PORT:-8081}:8080'
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_NUMBER=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_API_URL=https://api.open-meteo.com/v1/forecast
    depends_on:
      - redis

  app2:
    build: ./app
    container_name: app2
    ports:
      - '${APP2_PORT:-8082}:8080'
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_NUMBER=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_API_URL=https://api.open-meteo.com/v1/forecast
    depends_on:
      - redis

  app3:
    build: ./app
    container_name: app3
    ports:
      - '${APP3_PORT:-8083}:8080'
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_NUMBER=3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEATHER_API_URL=https://api.open-meteo.com/v1/forecast
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
